version: '2'
services:
    githubpages_hostings_local:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ../:/app
        ports:
          - '9004:8000'